substitutions:
  _ENV: dev  # This will be overridden in Cloud Build trigger per branch

steps:
  # Deploy Terraform
  - name: 'hashicorp/terraform:1.6.6'
    id: 'Terraform Apply'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd ${_ENV}/terraform
        terraform init
        terraform apply -auto-approve -var="project_id=$PROJECT_ID"

  # Deploy Backend App
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy Backend'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd ${_ENV}/backend
        gcloud app deploy --quiet

  # Deploy Frontend App
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy Frontend'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd ${_ENV}/frontend
        gcloud app deploy --quiet

logsBucket: "gs://multi-env-12"

timeout: 900s

