steps:
  - name: 'hashicorp/terraform:1.6.6'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "Deploying environment: $_BRANCH_NAME"
        cd terraform/$_BRANCH_NAME
        terraform init
        terraform apply -auto-approve

substitutions:
  _BRANCH_NAME: dev

timeout: "900s"
